services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    stdin_open: true
    tty: true
    build: ./api-dojo-system
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./api-dojo-system:/app
    command:
      - bash
      - -c
      - |
        npm install
        npm run start:dev

  frontend:
    stdin_open: true
    tty: true
    build: ./app-dojo-system
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./app-dojo-system:/app
    environment:
      - NG_CLI_ANALYTICS=false
    command:
      - bash
      - -c
      - |
        npm install
        npm start

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
